#!/bin/bash
passcracking() {
	export result="$(curl -s passcracking.com/index.php -d datafromuser=$md5sum|awk -F"$md5sum</td><td bgcolor=#FF0000>" {'print $2'}|grep td|awk -F"</td>" {'print $1'})"
}
milw0rm() {
	export result="$(curl -s http://milw0rm.com/cracker/search.php -d hash=$md5sum|awk -F"width=90>" {'print $3'}|grep TD|awk -F"</TD>" {'print $1'})"
}
check_result() {
	if [ "$result" != "" ]
	then	
		if echo $result |egrep -q "[a-zA-Z0-9]{32}"
		then
			md5sum=$result
			$1
		fi
		echo $result
		exit
	else
		echo "Hash not found"
		exit 1
	fi
}
if [ "$1" = "" ]
then
	echo "Usage: $0 [md5sum]"
	exit 1
else
	if echo $1 |egrep -q "[a-zA-Z0-9]{32}"
	then
		export md5sum=$1
	else
		echo "Argument isn't a md5sum"
		exit 1
	fi
fi
passcracking
check_result passcracking
milw0rm
check_result milw0rm
