#!/usr/bin/python
import re
import os
import commands
import dbus

exec2=commands.getoutput
fdisk=exec2('sudo fdisk -l')
fat='0b'
ntfs='7'

fdiskR=re.compile('/dev/(\D+\d)\s+\d+\s+\d+\s+\d+\s+['+fat+'|'+ntfs+']')
dev=fdiskR.findall(fdisk)

for hd in dev:
    exec2('mkdir /mnt/'+hd)
    mountE=exec2('sudo mount /dev/'+hd+' /mnt/'+hd)
